platform :ios, '9.0'

target 'SwiftDemoApp' do
  use_frameworks!

  pod 'AdmitadSDK', :git => 'https://github.com/dcherednikov/AdmitadSDK'

end

target 'ObjCDemoApp' do
  use_frameworks!

  pod 'AdmitadSDK', :git => 'https://github.com/dcherednikov/AdmitadSDK'

end
