platform :ios, '10.0'

target 'AdmitadSDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdmitadSDK
  pod 'Alamofire', '~> 5.1'
end
